In [2]:
import numpy as np
matrix_A=np.array([
    [1,2,3],
    [4,5,6],
    [99,100,101]
])
matrix_B=np.array([
    [12,15,56],
    [67,89,90],
    [66,77,88]
])
result=matrix_A + matrix_B
print("sum of matrix A and matrix B of:",result)

sum of matrix A and matrix B of: [[ 13  17  59]
 [ 71  94  96]
 [165 177 189]]


In [5]:
import numpy as np
matrix_A=np.array([
    [1,2,3],
    [4,5,6],
    [99,100,101]
])
transpose_matrix=np.transpose(matrix_A)
print("before transpose",matrix_A)
print("after transpose",transpose_matrix)

before transpose [[  1   2   3]
 [  4   5   6]
 [ 99 100 101]]
after transpose [[  1   4  99]
 [  2   5 100]
 [  3   6 101]]
